// Generated by scripts/gen-themes.mjs. Do not hand edit.
// The picker renders this list. It is generated so it cannot drift from themes.css.

export interface ThemeEntry {
  id: string;
  name: string;
  scheme: 'dark' | 'light';
  house: boolean;
}

export const THEMES: ThemeEntry[] = [
  {
    "id": "bbb-dark",
    "name": "BBB Dark",
    "scheme": "dark",
    "house": true
  },
  {
    "id": "bbb-light",
    "name": "BBB Light",
    "scheme": "light",
    "house": true
  },
  {
    "id": "hotdog-stand",
    "name": "Hot Dog Stand",
    "scheme": "light",
    "house": true
  },
  {
    "id": "github-dark",
    "name": "GitHub Dark",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "github-light",
    "name": "GitHub Light",
    "scheme": "light",
    "house": false
  },
  {
    "id": "dracula",
    "name": "Dracula",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "one-dark-pro",
    "name": "One Dark Pro",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "night-owl",
    "name": "Night Owl",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "tokyo-night",
    "name": "Tokyo Night",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "catppuccin-mocha",
    "name": "Catppuccin Mocha",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "catppuccin-latte",
    "name": "Catppuccin Latte",
    "scheme": "light",
    "house": false
  },
  {
    "id": "vitesse-dark",
    "name": "Vitesse Dark",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "vitesse-light",
    "name": "Vitesse Light",
    "scheme": "light",
    "house": false
  },
  {
    "id": "solarized-light",
    "name": "Solarized Light",
    "scheme": "light",
    "house": false
  },
  {
    "id": "nord",
    "name": "Nord",
    "scheme": "dark",
    "house": false
  },
  {
    "id": "monokai",
    "name": "Monokai",
    "scheme": "dark",
    "house": false
  }
];

export const DEFAULT_DARK = 'bbb-dark';
export const DEFAULT_LIGHT = 'bbb-light';
export const THEME_STORAGE_KEY = 'bbb-theme';
