import { defineEcConfig } from 'astro-expressive-code';
import ecThemes from './src/lib/ec-themes.generated.mjs';

/*
  Expressive Code lives here rather than in astro.config.mjs because themeCssSelector is
  a function, and the <Code> component needs the whole options object to survive a JSON
  round trip. A separate config file is how Expressive Code supports that.

  The themes are generated by scripts/gen-themes.mjs from the same resolved, contrast
  guarded tokens that produce themes.css. Feeding it the original VS Code themes instead
  would leave code blocks below AA while the chrome around them passed.
*/
export default defineEcConfig({
  themes: ecThemes,
  // All sixteen themes are emitted at once and scoped to the same [data-theme] attribute
  // the chrome switches on. That is what keeps a code block matching the panel it sits in
  // when a reader changes theme, with no rebuild and no flash.
  themeCssSelector: (theme) => `[data-theme="${theme.name}"]`,
  // Without this the first theme gets promoted to a media query default and wins over the
  // scoped blocks.
  useDarkModeMediaQuery: false,
  /*
    Expressive Code runs its own contrast pass over syntax colors, which would push the
    generated tokens somewhere other than where the guard put them and leave inline code
    in prose a different shade to the same token inside a block. The generator already
    clears 4.5 to 1 against all three surfaces, not just the code background, so this
    hands the job to the one guard that sees the whole picture.
  */
  minSyntaxHighlightingColorContrast: 0,
  styleOverrides: {
    uiFontFamily: 'var(--mono)',
    codeFontFamily: 'var(--mono)',
    codeFontSize: '0.8125rem',
    codeLineHeight: '1.7',
    borderColor: 'var(--line)',
    borderRadius: 'var(--r)',
    borderWidth: '1px'
  },
  frames: {
    showCopyToClipboardButton: true,
    copyButtonTooltipText: 'Copy this snippet'
  }
});
