/*
  Where the gates find a page of each archetype in dist.

  Both archetypes here are discovered rather than named, and both for the same reason,
  which is decision 117: a build must not go red over a content edit that touched no site
  code. A gate that names a slug fails on the Tuesday somebody renames a post, and the
  failure says nothing about the thing it was guarding.

  The disaster page learned this the hard way. It used to name a slug from
  src/config/disasters.seed.json, and when the wall started reading Supabase and the seed
  file went away, that URL stopped existing and the accessibility gate failed on a 404,
  reporting it as two axe problems. A gate that breaks because its fixture data moved is
  testing the fixture.

  The article page was the same mistake with a longer fuse and a worse blast radius. Its
  slug sat hardcoded in the same file as the disaster function that exists to avoid exactly
  that, between its definition and its call site, and it named a post in the src/content
  submodule, michaeljolley/content, which Michael edits without touching this repo at all.
  One SEO rename and the gate goes red on a build where nobody changed a line of site code.

  No line count here on purpose. The first draft of this comment carried one, it was wrong,
  the reply correcting it was wrong in the other direction, and both versions shipped in the
  same commit contradicting each other. A distance stops being true the next time anybody
  edits a file, and the point does not need it: a discovery function and a hardcoded slug
  lived in the same file, which is true at any distance.

  These are used by the accessibility gate and the share gate, so a rename now moves both
  in one place instead of leaving one of them stale.
*/

import { readdirSync, existsSync, readFileSync } from 'node:fs';

const DIST = 'dist';

/** True when dist carries a built page at this site relative path. */
function isBuilt(path) {
  return existsSync(`${DIST}${path}index.html`);
}

/** Built content URLs of one collection, sorted so the selected fixture is deterministic. */
function contentUrls(collection) {
  const file = 'src/config/taxonomy.json';
  if (!existsSync(file)) return [];

  const { entries } = JSON.parse(readFileSync(file, 'utf8'));
  return Object.entries(entries ?? {})
    .filter(([key]) => key.startsWith(`${collection}:`))
    .map(([, entry]) => entry.url)
    .filter(Boolean)
    .filter(isBuilt)
    .sort();
}

/**
 * The first published disaster's own page, or nothing when none have been published.
 *
 * Returns a list of [label, path] pairs so it can be spread into a page table, which is
 * how "no archetype yet" is said without a conditional in the middle of the table. The
 * archive's severity and sort views live under the same directory and are listed
 * explicitly by the caller, so they are excluded here rather than audited twice under the
 * wrong label.
 */
export function firstDisasterPage() {
  const dir = `${DIST}/dev-disasters`;
  if (!existsSync(dir)) return [];

  const views = new Set(['all', 'error', 'warning', 'info', 'hint']);
  const slug = readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !views.has(e.name))
    .map((e) => e.name)
    .sort()[0];

  return slug ? [['disaster', `/dev-disasters/${slug}/`]] : [];
}

/**
 * The first built article page, preferring one that carries a code block.
 *
 * Same shape and same contract as firstDisasterPage. The source is src/config/taxonomy.json
 * rather than a directory walk, because taxonomy holds content items and only content
 * items: the topic index and its articles and videos filter views are never in it, so
 * there is no exclusion list to keep in step with the routes. It is generated by pnpm gen,
 * which prebuild runs, so a renamed post moves the entry and the built page together.
 */
export function firstArticlePage() {
  const urls = contentUrls('blog');
  if (!urls.length) return [];

  /*
    Prefer a page with a code block on it. astro-expressive-code renders its own chrome
    from the same resolved theme as the rest of the site, which is the whole reason the
    theme generator resolves one theme for both, so an article without any code silently
    stops auditing half of what the contrast guard is for. Nine of the fifty built articles
    have no code in them, so this is a real choice and not a formality: sorted order lands
    on one that does today, and that is luck rather than intent.
  */
  const withCode = urls.find((url) =>
    readFileSync(`${DIST}${url}index.html`, 'utf8').includes('expressive-code')
  );

  return [['article', withCode ?? urls[0]]];
}

/**
 * The first built video detail page, or nothing when CI has no video_pages data.
 *
 * A catalogue video does not imply a site detail page. The latter is deliberately backed
 * by Supabase, so a keyless build normally has none and callers must provide an archive
 * fallback if they always need a video surface.
 */
export function firstVideoPage() {
  const url = contentUrls('videos')[0];
  return url ? [['video', url]] : [];
}
