/*
  Self hosted fonts.

  The design system asks for three families by their real names, so the generated CSS uses
  those names rather than the "Fraunces Variable" style names Fontsource ships. Nothing in
  app.css has to know where the files came from.

  This exists because the alternative, a Google Fonts stylesheet in the head, is a render
  blocking request to a third party before a single word can paint, and it tells Google
  about every reader. Self hosting removes both. The files land in public/fonts, which is
  gitignored, because Fontsource is the source of truth and a copied binary in the repo
  would only ever drift away from it.

  Only the latin and latin-ext subsets are shipped. The site is written in English, and a
  reader who needs Cyrillic or Vietnamese gets the fallback stack, which is what they would
  have got from an unsubsetted webfont on a slow connection anyway.
*/

import { mkdir, readFile, writeFile, copyFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const OUT_DIR = join(ROOT, 'public', 'fonts');
const OUT_CSS = join(ROOT, 'src', 'styles', 'fonts.generated.css');

const SUBSETS = ['latin', 'latin-ext'];

/*
  Fraunces ships one file per combination of variable axes. The design sets SOFT and WONK
  on every heading, and only the "full" build carries both, so the cheaper single axis
  builds are not an option here.
*/
const FAMILIES = [
  {
    family: 'Fraunces',
    pkg: '@fontsource-variable/fraunces',
    /* No italic. The only italics in the design system are on the mono face, and a
       synthesized oblique on the rare emphasised heading is not worth 150 KB. */
    css: ['full.css']
  },
  {
    family: 'Atkinson Hyperlegible Next',
    pkg: '@fontsource-variable/atkinson-hyperlegible-next',
    /* Body copy, so real italics matter. Fontsource keeps them in a separate stylesheet. */
    css: ['index.css', 'wght-italic.css']
  },
  {
    family: 'Fira Code',
    pkg: '@fontsource-variable/fira-code',
    css: ['index.css']
  }
];

/* Fontsource writes one @font-face per subset per style, each with a comment naming it.
   Parsing them is more reliable than hand copying unicode ranges that change with each
   Unicode release. */
function parseFaces(css) {
  const faces = [];
  const re = /@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const block = m[1];
    const get = (prop) => block.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1]?.trim();
    const src = get('src');
    const file = src?.match(/url\(\.\/files\/([^)]+)\)/)?.[1];
    if (!file) continue;
    faces.push({
      file,
      style: get('font-style') ?? 'normal',
      weight: get('font-weight') ?? '400',
      unicodeRange: get('unicode-range')
    });
  }
  return faces;
}

/* The subset name sits between the family slug and the axis name in the file name, so it
   has to be matched against the longest candidate first or "latin" swallows "latin-ext". */
function subsetOf(file) {
  const ordered = [...SUBSETS].sort((a, b) => b.length - a.length);
  return ordered.find((s) => file.includes(`-${s}-`));
}

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const blocks = [];
let copied = 0;

for (const { family, pkg, css } of FAMILIES) {
  for (const sheet of css) {
    const cssPath = fileURLToPath(await import.meta.resolve(`${pkg}/${sheet}`));
    const pkgDir = dirname(cssPath);
    const faces = parseFaces(await readFile(cssPath, 'utf8'));

    for (const face of faces) {
      const subset = subsetOf(face.file);
      if (!subset) continue;

      await copyFile(join(pkgDir, 'files', face.file), join(OUT_DIR, face.file));
      copied++;

      blocks.push(
        [
          `@font-face {`,
          `  font-family: '${family}';`,
          `  font-style: ${face.style};`,
          `  font-weight: ${face.weight};`,
          /* swap rather than optional, because the design leans on Fraunces hard enough
             that a permanent fallback would not be the same site. */
          `  font-display: swap;`,
          `  src: url(/fonts/${face.file}) format('woff2-variations');`,
          face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
          `}`
        ]
          .filter(Boolean)
          .join('\n')
      );
    }
  }
}

const header = `/*
  GENERATED by scripts/gen-fonts.mjs. Do not edit.

  Run \`pnpm fonts\` to rebuild it, or just \`pnpm build\`, which runs it for you.
*/\n\n`;

await writeFile(OUT_CSS, header + blocks.join('\n\n') + '\n');

console.log(`fonts: ${copied} files copied, ${blocks.length} faces declared.`);
