/*
  Baseline. Captured from the production schema of project bvyerlczpakdlfvybkev.

  Everything below predates this repo. It was built through Studio and through six
  migrations that were never checked in, so a fresh database started empty and every
  later migration was written against a schema nobody could read. This file is that
  schema, written down.

  It is reconstructed from the catalog rather than dumped, so it carries tables,
  identity columns, constraints, indexes, RLS, policies, functions and triggers, and
  nothing else. Grants, publications, storage buckets, cron jobs and the auth schema
  are not here.

  It is already applied on production, so never push it there. After linking, run
  `supabase migration repair --status applied 20260101000000`. It exists so that a
  local `supabase db reset` and a preview branch both come up with a database that
  looks like the real one.

  Do not edit. Change the schema with a new migration.
*/

-- Tables, identity columns and constraints

create table public.analytics_events (
  id uuid default gen_random_uuid() not null,
  session_id uuid,
  user_id text,
  created_at timestamp with time zone default now() not null,
  domain text not null,
  path text not null,
  querystring text,
  referrer text,
  browser text,
  browser_version text,
  os text,
  device_type text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  country text,
  timezone text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text
);
alter table public.analytics_events add constraint analytics_events_pkey PRIMARY KEY (id);
alter table public.analytics_events add constraint analytics_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES analytics_sessions(id) ON DELETE CASCADE;

create table public.analytics_sessions (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  last_seen_at timestamp with time zone default now() not null
);
alter table public.analytics_sessions add constraint analytics_sessions_pkey PRIMARY KEY (id);

create table public.announcements (
  id bigint generated by default as identity not null,
  title text not null,
  subtitle text,
  command text,
  message text,
  expiration_date date
);
alter table public.announcements add constraint announcements_pkey PRIMARY KEY (id);

create table public.batches (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  type text not null,
  status text not null,
  "openAIFileId" text,
  "openAIBatchId" text
);
alter table public.batches add constraint batches_pkey PRIMARY KEY (id);

create table public.blogs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  "pageTitle" text not null,
  "pageUrl" text not null,
  "pageBody" text not null,
  "batchId" bigint,
  status text default 'new'::text not null,
  "genTitles" text,
  "genDescription" text,
  "genBody" text,
  "releaseDate" date,
  "isShared" boolean default false not null,
  slug text,
  blog_image text,
  blog_image_alt text,
  social_bluesky_summary text,
  social_x_summary text,
  social_linkedin_summary text,
  social_summary text
);
alter table public.blogs add constraint blogs_pkey PRIMARY KEY (id);
alter table public.blogs add constraint "blogs_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES batches(id) ON UPDATE CASCADE ON DELETE SET NULL;

create table public.domains (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  domain text not null,
  "isLowQuality" boolean default true not null,
  "isLowSocial" boolean default false not null,
  "isBBB" boolean default false not null
);
alter table public.domains add constraint domains_pkey PRIMARY KEY (id);

create table public."dripEmails" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  "dripDate" date not null,
  "isApproved" boolean default false not null,
  "isFull" boolean default false not null,
  "isGenerated" boolean default false not null,
  social_summary text,
  "batchId" bigint,
  "bodyHTML" text,
  "isShared" boolean default false not null,
  "openingMarkdown" text,
  social_x_summary text,
  social_bluesky_summary text,
  social_linkedin_summary text,
  "oneLiner" text,
  "bodyMarkdown" text,
  "isScheduled" boolean default false
);
alter table public."dripEmails" add constraint "dripEmails_pkey" PRIMARY KEY (id);
alter table public."dripEmails" add constraint "dripEmails_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES batches(id);

create table public.drips (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  "pageTitle" text not null,
  "pageUrl" text not null,
  "pageBody" text not null,
  status text default 'new'::text not null,
  "dripEmailId" bigint,
  "batchId" bigint,
  summary text,
  "isShared" boolean default false not null,
  social_body text,
  "isHot" boolean default false not null,
  "isDotNet" boolean default false not null,
  "xUrl" text,
  "linkedinUrl" text,
  "blueskyUrl" text,
  "webUrl" text,
  "emailUrl" text
);
alter table public.drips add constraint drips_pkey PRIMARY KEY (id);
alter table public.drips add constraint "drips_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES batches(id) ON UPDATE CASCADE ON DELETE SET NULL;
alter table public.drips add constraint "drips_dripEmailId_fkey" FOREIGN KEY ("dripEmailId") REFERENCES "dripEmails"(id) ON UPDATE CASCADE ON DELETE SET NULL;

create table public.ideas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  "batchId" bigint,
  "pageUrl" text not null,
  "pageBody" text,
  "pageTitle" text,
  source text not null,
  "isApproved" boolean default false not null,
  "isDrip" boolean default false not null,
  "isVideo" boolean default false not null,
  "isProcessed" boolean default false not null,
  "isBlog" boolean default false not null,
  submitted_name text,
  submitted_email text,
  thankyou_sent boolean default false not null,
  giveaway_link text,
  "cleanPageUrl" text not null
);
alter table public.ideas add constraint ideas_pkey PRIMARY KEY (id);
alter table public.ideas add constraint "ideas_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES batches(id) ON UPDATE CASCADE ON DELETE SET NULL;

create table public.productions (
  id uuid default gen_random_uuid() not null,
  issue_number integer not null,
  type text not null,
  short_index smallint,
  title text default ''::text not null,
  status text default 'Recording'::text not null,
  release_date date,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);
alter table public.productions add constraint productions_issue_number_type_short_index_key UNIQUE (issue_number, type, short_index);
alter table public.productions add constraint productions_pkey PRIMARY KEY (id);
alter table public.productions add constraint productions_check CHECK ((((type = 'main'::text) AND (short_index IS NULL)) OR ((type = 'short'::text) AND ((short_index >= 0) AND (short_index <= 2)))));
alter table public.productions add constraint productions_status_check CHECK ((status = ANY (ARRAY['Recording'::text, 'Editing'::text, 'Final Checks'::text, 'Staged'::text, 'Published'::text])));
alter table public.productions add constraint productions_type_check CHECK ((type = ANY (ARRAY['main'::text, 'short'::text])));

create table public.replacements (
  "fromWord" text not null,
  "toWord" text not null
);
alter table public.replacements add constraint replacements_pkey PRIMARY KEY ("fromWord");

create table public.shorturls (
  slug text not null,
  target text not null
);
alter table public.shorturls add constraint shorturls_pkey PRIMARY KEY (slug);

create table public.social_contacts (
  id uuid default gen_random_uuid() not null,
  name text not null,
  x_handle text,
  linkedin_handle text,
  bluesky_handle text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  bluesky_did text,
  linkedin_urn text
);
alter table public.social_contacts add constraint social_contacts_pkey PRIMARY KEY (id);

create table public."streamEvents" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  "eventType" text not null,
  message text,
  login text not null,
  "streamDate" text not null,
  quantity bigint,
  platform text default 'twitch'::text not null
);
alter table public."streamEvents" add constraint streamevents_pkey PRIMARY KEY (id);

create table public."streamUsers" (
  login text not null,
  avatar_url text not null,
  display_name text,
  "lastUpdated" timestamp without time zone,
  platform text default 'twitch'::text not null
);
alter table public."streamUsers" add constraint streamusers_login_platform_unique UNIQUE (login, platform);

create table public.streams (
  stream_date date not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  total_events integer default 0,
  total_chats integer default 0,
  unique_chatters integer default 0,
  unique_viewers integer default 0,
  total_subs integer default 0,
  total_giftsubs integer default 0,
  total_giftsub_count integer default 0,
  total_cheers integer default 0,
  total_cheer_bits integer default 0,
  total_raids integer default 0,
  total_raid_viewers integer default 0,
  total_follows integer default 0
);
alter table public.streams add constraint streams_pkey PRIMARY KEY (stream_date);

create table public.videos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  "pageTitle" text not null,
  "pageUrl" text not null,
  "pageBody" text not null,
  "batchId" bigint,
  "genTitles" text,
  "genDescription" text,
  "genShortScripts" text,
  "genScript" text,
  status text default 'new'::text,
  "genTags" text
);
alter table public.videos add constraint videos_pkey PRIMARY KEY (id);
alter table public.videos add constraint "videos_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES batches(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Indexes

CREATE INDEX "drips_batchId_idx" ON public.drips USING btree ("batchId");
CREATE INDEX drips_created_at_idx ON public.drips USING btree (created_at);
CREATE INDEX "drips_dripEmailId_idx" ON public.drips USING btree ("dripEmailId");
CREATE INDEX "drips_isDotNet_idx" ON public.drips USING btree ("isDotNet");
CREATE INDEX "drips_isHot_idx" ON public.drips USING btree ("isHot");
CREATE INDEX "drips_isShared_idx" ON public.drips USING btree ("isShared");
CREATE INDEX drips_status_idx ON public.drips USING btree (status);
CREATE INDEX "ideas_cleanPageUrl_idx" ON public.ideas USING btree ("cleanPageUrl");
CREATE INDEX "ideas_isProcessed_idx" ON public.ideas USING btree ("isProcessed");
CREATE INDEX ideas_thankyou_sent_idx ON public.ideas USING btree (thankyou_sent);
CREATE INDEX idx_analytics_events_created_at ON public.analytics_events USING btree (created_at);
CREATE INDEX idx_analytics_events_domain ON public.analytics_events USING btree (domain);
CREATE INDEX idx_analytics_events_domain_path ON public.analytics_events USING btree (domain, path);
CREATE INDEX idx_analytics_events_session_id ON public.analytics_events USING btree (session_id);
CREATE INDEX idx_analytics_events_user_id ON public.analytics_events USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_analytics_sessions_last_seen ON public.analytics_sessions USING btree (last_seen_at);
CREATE INDEX idx_productions_issue ON public.productions USING btree (issue_number);
CREATE INDEX idx_productions_status ON public.productions USING btree (status);
CREATE INDEX "streamEvents_created_at_idx" ON public."streamEvents" USING btree (created_at);
CREATE INDEX "streamEvents_streamDate_idx" ON public."streamEvents" USING btree ("streamDate");

-- Row level security

alter table public.analytics_events enable row level security;
alter table public.analytics_sessions enable row level security;
alter table public.announcements enable row level security;
alter table public.batches enable row level security;
alter table public.blogs enable row level security;
alter table public.domains enable row level security;
alter table public."dripEmails" enable row level security;
alter table public.drips enable row level security;
alter table public.ideas enable row level security;
alter table public.productions enable row level security;
alter table public.replacements enable row level security;
alter table public.shorturls enable row level security;
alter table public.social_contacts enable row level security;
alter table public."streamEvents" enable row level security;
alter table public."streamUsers" enable row level security;
alter table public.streams enable row level security;
alter table public.videos enable row level security;

-- Policies

create policy "Authenticated users
  can read analytics_events" on public.analytics_events as PERMISSIVE for SELECT to authenticated using (true);
create policy "Allow mike full access to analytics_sessions" on public.analytics_sessions as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to announcements" on public.announcements as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to batches" on public.batches as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to blogs" on public.blogs as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to domains" on public.domains as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid)) with check ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to dripEmails" on public."dripEmails" as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to drips" on public.drips as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to ideas" on public.ideas as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow all access" on public.productions as PERMISSIVE for ALL to public using (true) with check (true);
create policy "Allow mike full access to replacements" on public.replacements as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to shorturls" on public.shorturls as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Authenticated users can delete social_contacts" on public.social_contacts as PERMISSIVE for DELETE to public using ((auth.role() = 'authenticated'::text));
create policy "Authenticated users can insert social_contacts" on public.social_contacts as PERMISSIVE for INSERT to public with check ((auth.role() = 'authenticated'::text));
create policy "Authenticated users can read social_contacts" on public.social_contacts as PERMISSIVE for SELECT to public using ((auth.role() = 'authenticated'::text));
create policy "Authenticated users can update social_contacts" on public.social_contacts as PERMISSIVE for UPDATE to public using ((auth.role() = 'authenticated'::text)) with check ((auth.role() = 'authenticated'::text));
create policy "Allow mike full access to streamEvents" on public."streamEvents" as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid)) with check ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to streamUsers" on public."streamUsers" as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to streams" on public.streams as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));
create policy "Allow mike full access to videos" on public.videos as PERMISSIVE for ALL to public using ((( SELECT auth.uid() AS uid) = '0b820780-f86e-4710-a383-a86aa3506766'::uuid));

-- Functions

CREATE OR REPLACE FUNCTION public.compute_all_stream_stats()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
   DECLARE
     stream_rec RECORD;
   BEGIN
     FOR stream_rec IN
       SELECT DISTINCT "streamDate"::date as sd
       FROM public."streamEvents"
       WHERE "streamDate"::date < CURRENT_DATE
       ORDER BY sd
     LOOP
       PERFORM public.compute_stream_stats(stream_rec.sd);
     END LOOP;
   END;
   $function$
;

CREATE OR REPLACE FUNCTION public.compute_stream_stats(target_date date)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
   DECLARE
     v_total_events integer;
     v_total_chats integer;
     v_unique_chatters integer;
     v_unique_viewers integer;
     v_total_subs integer;
     v_total_giftsubs integer;
     v_total_giftsub_count integer;
     v_total_cheers integer;
     v_total_cheer_bits integer;
     v_total_raids integer;
     v_total_raid_viewers integer;
     v_total_follows integer;
   BEGIN
     -- Count total events (excluding join/part)
     SELECT COUNT(*) INTO v_total_events
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" NOT IN ('onJoin', 'onPart');

     -- Count chats
     SELECT COUNT(*) INTO v_total_chats
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'onChatMessage';

     -- Count unique chatters
     SELECT COUNT(DISTINCT login) INTO v_unique_chatters
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'onChatMessage';

     -- Count unique viewers (from ANY event for that date)
     SELECT COUNT(DISTINCT login) INTO v_unique_viewers
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text;

     -- Count subs
     SELECT COUNT(*) INTO v_total_subs
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'twitch:sub';

     -- Count gift subs and total gifted
     SELECT COUNT(*), COALESCE(SUM(quantity), 0) INTO v_total_giftsubs,
  v_total_giftsub_count
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'twitch:giftsub';

     -- Count cheers and total bits
     SELECT COUNT(*), COALESCE(SUM(quantity), 0) INTO v_total_cheers, v_total_cheer_bits
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'twitch:cheer';

     -- Count raids and total viewers
     SELECT COUNT(*), COALESCE(SUM(quantity), 0) INTO v_total_raids,
  v_total_raid_viewers
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'twitch:raid';

     -- Count follows
     SELECT COUNT(*) INTO v_total_follows
     FROM public."streamEvents"
     WHERE "streamDate" = target_date::text
       AND "eventType" = 'twitch:follow';

     -- Upsert the stats
     INSERT INTO public.streams (
       stream_date, updated_at, total_events, total_chats, unique_chatters,
  unique_viewers,
       total_subs, total_giftsubs, total_giftsub_count, total_cheers, total_cheer_bits,
       total_raids, total_raid_viewers, total_follows
     ) VALUES (
       target_date, now(), v_total_events, v_total_chats, v_unique_chatters,
  v_unique_viewers,
       v_total_subs, v_total_giftsubs, v_total_giftsub_count, v_total_cheers,
  v_total_cheer_bits,
       v_total_raids, v_total_raid_viewers, v_total_follows
     )
     ON CONFLICT (stream_date) DO UPDATE SET
       updated_at = now(),
       total_events = EXCLUDED.total_events,
       total_chats = EXCLUDED.total_chats,
       unique_chatters = EXCLUDED.unique_chatters,
       unique_viewers = EXCLUDED.unique_viewers,
       total_subs = EXCLUDED.total_subs,
       total_giftsubs = EXCLUDED.total_giftsubs,
       total_giftsub_count = EXCLUDED.total_giftsub_count,
       total_cheers = EXCLUDED.total_cheers,
       total_cheer_bits = EXCLUDED.total_cheer_bits,
       total_raids = EXCLUDED.total_raids,
       total_raid_viewers = EXCLUDED.total_raid_viewers,
       total_follows = EXCLUDED.total_follows;
   END;
   $function$
;

CREATE OR REPLACE FUNCTION public.ensure_stream_exists()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
   BEGIN
     INSERT INTO public.streams (stream_date)
     VALUES (NEW."streamDate"::date)
     ON CONFLICT (stream_date) DO NOTHING;
     RETURN NEW;
   END;
   $function$
;

CREATE OR REPLACE FUNCTION public.get_analytics_summary(start_date timestamp with time zone, end_date timestamp with time zone, filter_domain text DEFAULT NULL::text, filter_browser text DEFAULT NULL::text, filter_device text DEFAULT NULL::text, filter_path text DEFAULT NULL::text, filter_referrer text DEFAULT NULL::text, filter_utm_source text DEFAULT NULL::text, filter_utm_medium text DEFAULT NULL::text, filter_utm_campaign text DEFAULT NULL::text, filter_utm_content text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  result jsonb;
BEGIN
  WITH filtered AS (
    SELECT *
    FROM "analytics_events"
    WHERE created_at >= start_date
      AND created_at <= end_date
      AND domain NOT ILIKE '%netlify.app%'
      AND domain NOT ILIKE '%localhost%'
      AND path NOT ILIKE '%wp-%'
      AND path NOT ILIKE '%xmlrpc%'
      AND path NOT ILIKE '%sitemap%'
      AND path NOT ILIKE '%/admin%'
      AND path NOT ILIKE '%/user%'
      AND path NOT ILIKE '%.json'
      AND path NOT ILIKE '%.txt'
      AND path NOT ILIKE '%.php'
      AND path NOT ILIKE '%.ico'
      AND path NOT ILIKE '%.png'
      AND path NOT ILIKE '%.jpg'
      AND path NOT ILIKE '%.jpeg'
      AND path NOT ILIKE '%.gif'
      AND path NOT ILIKE '%.svg'
      AND path NOT ILIKE '%.css'
      AND path NOT ILIKE '%.js'
      AND path NOT ILIKE '%.webp'
      AND path NOT ILIKE '%.woff%'
      AND path NOT ILIKE '%.xml'
      AND path != '/login'
      AND path != '/.env'
      AND (filter_domain IS NULL OR domain = filter_domain)
      AND (filter_browser IS NULL OR browser = filter_browser)
      AND (filter_device IS NULL OR device_type = filter_device)
      AND (filter_path IS NULL OR path = filter_path)
      AND (filter_referrer IS NULL OR
        CASE
          WHEN filter_referrer = 'Direct' THEN (referrer IS NULL OR referrer = '')
          ELSE (
            CASE
              WHEN referrer ~ '^https?://' THEN split_part(split_part(referrer, '://', 2), '/', 1)
              ELSE referrer
            END
          ) = filter_referrer
        END
      )
      AND (filter_utm_source IS NULL OR utm_source = filter_utm_source)
      AND (filter_utm_medium IS NULL OR utm_medium = filter_utm_medium)
      AND (filter_utm_campaign IS NULL OR utm_campaign = filter_utm_campaign)
      AND (filter_utm_content IS NULL OR utm_content = filter_utm_content)
  ),
  summary AS (
    SELECT
      count(*)::int AS total_views,
      count(DISTINCT session_id)::int AS unique_sessions
    FROM filtered
  ),
  top_browser AS (
    SELECT browser AS name, count(*)::int AS cnt
    FROM filtered
    GROUP BY browser
    ORDER BY cnt DESC
    LIMIT 1
  ),
  top_utm AS (
    SELECT utm_source AS name, count(*)::int AS cnt
    FROM filtered
    WHERE utm_source IS NOT NULL
    GROUP BY utm_source
    ORDER BY cnt DESC
    LIMIT 1
  ),
  top_pages AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT path, count(*)::int AS cnt,
        mode() WITHIN GROUP (ORDER BY utm_medium) AS top_medium
      FROM filtered
      GROUP BY path
      ORDER BY cnt DESC
      LIMIT 10
    ) t
  ),
  referrer_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT
        CASE
          WHEN referrer IS NULL OR referrer = '' THEN ''
          ELSE (
            CASE
              WHEN referrer ~ '^https?://' THEN split_part(split_part(referrer,
'://', 2), '/', 1)
              ELSE referrer
            END
          )
        END AS referrer,
        count(*)::int AS cnt
      FROM filtered
      GROUP BY 1
      ORDER BY cnt DESC
      LIMIT 10
    ) t
  ),
  browser_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT COALESCE(browser, 'Unknown') AS name, count(*)::int AS cnt
      FROM filtered
      GROUP BY 1
      ORDER BY cnt DESC
      LIMIT 5
    ) t
  ),
  device_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT COALESCE(device_type, 'unknown') AS name, count(*)::int AS cnt
      FROM filtered
      GROUP BY 1
      ORDER BY cnt DESC
    ) t
  ),
  utm_source_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT utm_source AS name, count(*)::int AS cnt
      FROM filtered
      WHERE utm_source IS NOT NULL
      GROUP BY utm_source
      ORDER BY cnt DESC
      LIMIT 10
    ) t
  ),
  utm_medium_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT utm_medium AS name, count(*)::int AS cnt
      FROM filtered
      WHERE utm_medium IS NOT NULL
      GROUP BY utm_medium
      ORDER BY cnt DESC
      LIMIT 10
    ) t
  ),
  utm_campaign_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT utm_campaign AS name, count(*)::int AS cnt
      FROM filtered
      WHERE utm_campaign IS NOT NULL
      GROUP BY utm_campaign
      ORDER BY cnt DESC
      LIMIT 10
    ) t
  ),
  utm_content_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.cnt DESC) AS data
    FROM (
      SELECT utm_content AS name, count(*)::int AS cnt
      FROM filtered
      WHERE utm_content IS NOT NULL
      GROUP BY utm_content
      ORDER BY cnt DESC
      LIMIT 10
    ) t
  ),
  daily_data AS (
    SELECT jsonb_agg(row_to_json(t)::jsonb ORDER BY t.period) AS data
    FROM (
      SELECT created_at::date::text AS period, count(*)::int AS cnt
      FROM filtered
      GROUP BY 1
      ORDER BY 1
    ) t
  )
  SELECT jsonb_build_object(
    'total_views', s.total_views,
    'unique_sessions', s.unique_sessions,
    'top_browser', (SELECT name FROM top_browser),
    'top_utm_source', (SELECT name FROM top_utm),
    'top_pages', COALESCE((SELECT data FROM top_pages), '[]'::jsonb),
    'referrers', COALESCE((SELECT data FROM referrer_data), '[]'::jsonb),
    'browsers', COALESCE((SELECT data FROM browser_data), '[]'::jsonb),
    'devices', COALESCE((SELECT data FROM device_data), '[]'::jsonb),
    'utm_sources', COALESCE((SELECT data FROM utm_source_data), '[]'::jsonb),
    'utm_mediums', COALESCE((SELECT data FROM utm_medium_data), '[]'::jsonb),
    'utm_campaigns', COALESCE((SELECT data FROM utm_campaign_data), '[]'::jsonb),
    'utm_content', COALESCE((SELECT data FROM utm_content_data), '[]'::jsonb),
    'daily_views', COALESCE((SELECT data FROM daily_data), '[]'::jsonb)
  ) INTO result
  FROM summary s;

  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_dashboard_counts()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT jsonb_build_object(
    -- Ideas
    'ideasNew',        (SELECT COUNT(*) FROM ideas WHERE "isProcessed" = false AND "isApproved" = false),
    'ideasApproved',   (SELECT COUNT(*) FROM ideas WHERE "isApproved" = true  AND "isProcessed" = false),
    'ideasProcessed',  (SELECT COUNT(*) FROM ideas WHERE "isProcessed" = true),
    'ideasAll',        (SELECT COUNT(*) FROM ideas),

    -- Drips
    'dripsNew',        (SELECT COUNT(*) FROM drips WHERE status = 'new'),
    'dripsSummaryGen', (SELECT COUNT(*) FROM drips WHERE status = 'drip-summary-gen'),
    'dripsPending',    (SELECT COUNT(*) FROM drips WHERE status = 'pending'),
    'dripsReady',      (SELECT COUNT(*) FROM drips WHERE status = 'ready' AND "dripEmailId" IS NULL),
    'dripsQueued',     (SELECT COUNT(*) FROM drips WHERE status = 'ready' AND "dripEmailId" IS NOT NULL),
    'dripsSent',       (SELECT COUNT(*) FROM drips WHERE status = 'sent'),
    'dripsCompleted',  (SELECT COUNT(*) FROM drips WHERE status = 'completed'),
    'dripsAll',        (SELECT COUNT(*) FROM drips),

    -- Videos
    'videosNew',        (SELECT COUNT(*) FROM videos WHERE status = 'new' OR status IS NULL),
    'videosVideoGen',   (SELECT COUNT(*) FROM videos WHERE status = 'video-gen'),
    'videosScriptsDone',(SELECT COUNT(*) FROM videos WHERE status = 'scripts_done'),
    'videosApproved',   (SELECT COUNT(*) FROM videos WHERE status = 'approved'),
    'videosDone',       (SELECT COUNT(*) FROM videos WHERE status = 'done'),
    'videosRejected',   (SELECT COUNT(*) FROM videos WHERE status = 'rejected'),
    'videosAll',        (SELECT COUNT(*) FROM videos),

    -- Blogs
    'blogsNew',         (SELECT COUNT(*) FROM blogs WHERE status = 'new' OR status IS NULL),
    'blogsBlogGen',     (SELECT COUNT(*) FROM blogs WHERE status = 'blog-gen'),
    'blogsReady',       (SELECT COUNT(*) FROM blogs WHERE status = 'ready'),
    'blogsImageGen',    (SELECT COUNT(*) FROM blogs WHERE status = 'image-gen'),
    'blogsApproved',    (SELECT COUNT(*) FROM blogs WHERE status = 'approved'),
    'blogsQueued',      (SELECT COUNT(*) FROM blogs WHERE "releaseDate" > CURRENT_DATE),
    'blogsDone',        (SELECT COUNT(*) FROM blogs WHERE "releaseDate" <= CURRENT_DATE),
    'blogsAll',         (SELECT COUNT(*) FROM blogs),

    -- DripEmails
    'dripEmailsNew',       (SELECT COUNT(*) FROM "dripEmails" WHERE "isApproved" = false AND "isFull" = false AND "isGenerated" = false AND "isShared" = false),
    'dripEmailsFull',      (SELECT COUNT(*) FROM "dripEmails" WHERE "isFull" = true  AND "isGenerated" = false),
    'dripEmailsGenerated', (SELECT COUNT(*) FROM "dripEmails" WHERE "isGenerated" = true AND "isApproved" = false),
    'dripEmailsApproved',  (SELECT COUNT(*) FROM "dripEmails" WHERE "isApproved" = true AND "isScheduled" = false),
    'dripEmailsScheduled', (SELECT COUNT(*) FROM "dripEmails" WHERE "isScheduled" = true AND "dripDate" > CURRENT_DATE),
    'dripEmailsSent',      (SELECT COUNT(*) FROM "dripEmails" WHERE "isScheduled" = true AND "isShared" = false AND "dripDate" < CURRENT_DATE),
    'dripEmailsDone',      (SELECT COUNT(*) FROM "dripEmails" WHERE "isShared" = true),
    'dripEmailsAll',       (SELECT COUNT(*) FROM "dripEmails")
  );
$function$
;

CREATE OR REPLACE FUNCTION public.get_distinct_event_types()
 RETURNS TABLE(event_type text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT DISTINCT "eventType"::text AS event_type
  FROM "streamEvents"
  WHERE "eventType" IS NOT NULL
  ORDER BY event_type;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_leaderboard()
 RETURNS TABLE(login text, event_count bigint, message_count bigint, last_active timestamp with time zone, raid_count bigint, raid_total bigint, sub_count bigint, giftsub_count bigint, giftsub_total bigint, cheer_count bigint, cheer_total bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT
    e.login::text,
    COUNT(*)                                                                   AS event_count,
    COUNT(*) FILTER (WHERE e."eventType" = 'onChatMessage')                   AS message_count,
    MAX(e.created_at)                                                         AS last_active,
    COUNT(*) FILTER (WHERE e."eventType" = 'twitch:raid')                     AS raid_count,
    COALESCE(SUM(e.quantity) FILTER (WHERE e."eventType" = 'twitch:raid'), 0) AS raid_total,
    COUNT(*) FILTER (WHERE e."eventType" = 'twitch:sub')                      AS sub_count,
    COUNT(*) FILTER (WHERE e."eventType" = 'twitch:giftsub')                  AS giftsub_count,
    COALESCE(SUM(e.quantity) FILTER (WHERE e."eventType" = 'twitch:giftsub'), 0) AS giftsub_total,
    COUNT(*) FILTER (WHERE e."eventType" = 'twitch:cheer')                    AS cheer_count,
    COALESCE(SUM(e.quantity) FILTER (WHERE e."eventType" = 'twitch:cheer'), 0) AS cheer_total
  FROM "streamEvents" e
  WHERE e."eventType" NOT IN ('onJoin', 'onPart')
    AND e.login IS NOT NULL
  GROUP BY e.login;
$function$
;

CREATE OR REPLACE FUNCTION public.update_productions_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$
;

-- Triggers

CREATE TRIGGER ensure_stream_on_event AFTER INSERT ON public."streamEvents" FOR EACH ROW EXECUTE FUNCTION ensure_stream_exists();
CREATE TRIGGER trg_productions_updated_at BEFORE UPDATE ON public.productions FOR EACH ROW EXECUTE FUNCTION update_productions_updated_at();
