/*
  Email notifications. Decision 15.

  Three types, opt out per type, one click unsubscribe. This migration adds the queue and
  the triggers that fill it. Rendering and sending live in the site, in
  src/lib/notifications.ts, because an email template written in SQL is a template nobody
  will ever change.

  Two shapes matter here.

  First, a queue rather than a direct send. Every one of the three events is a row change
  somebody makes in Studio or a comment somebody posts, and none of those should fail
  because a mail provider is having a bad afternoon. The trigger writes a row. Something
  else drains it, retries, and gives up loudly rather than silently.

  Second, no email address anywhere in this table. The address lives in auth.users and is
  read at send time. Copying it into a queue row means a deleted account can still be
  emailed by a row that outlived it, which is precisely the promise decision 17 makes and
  precisely the way that promise gets broken by accident.
*/

-- Featured is a real act, not a side effect ----------------------------------------------

/*
  There was no way to feature a story before this column, which meant the story_featured
  preference switched something that could never happen. The front page lead was simply
  the newest published row, so nobody was ever chosen and nobody could be told they were.

  Setting this in Studio is the whole mechanism, which is the correct amount of admin
  tooling for v1: one column, one timestamp, and the front page and the badge and the
  email all key off it.
*/
alter table public.disasters add column featured_at timestamptz;

create index disasters_featured_idx on public.disasters (featured_at desc)
  where featured_at is not null and status = 'published';

-- The queue ------------------------------------------------------------------------------

create table public.email_outbox (
  id bigint primary key generated by default as identity,

  kind text not null check (kind in ('story_published', 'story_featured', 'comment_reply')),

  /* Who is being written to. Cascades, so deleting an account empties its queue. */
  profile_id uuid not null references public.profiles (id) on delete cascade,

  /*
    Everything the template needs that is not the address. Slugs, titles, a comment
    excerpt. Captured at enqueue time on purpose: a story renamed between the event and
    the send should still produce an email about the thing that happened.
  */
  payload jsonb not null default '{}'::jsonb,

  /*
    One send per event, enforced by the database rather than by the drain being careful.
    A status column flipped to published, back, and forward again is an ordinary Studio
    afternoon, and it should not produce three emails.
  */
  dedupe_key text not null unique,

  created_at timestamptz not null default now(),
  sent_at timestamptz,

  /*
    Attempts and the last error, so a queue that is stuck says why. Nothing reads these
    yet beyond the drain's own backoff, and that is fine: the alternative is discovering
    a week of failures with no record of what failed.
  */
  attempts integer not null default 0,
  last_error text,
  last_attempt_at timestamptz
);

create index email_outbox_pending_idx on public.email_outbox (created_at)
  where sent_at is null;

alter table public.email_outbox enable row level security;

/*
  No policies at all, which means no policy can match, which means anon and authenticated
  can do nothing here. Only the service role touches this table. Spelled out rather than
  left implicit because an empty policy list reads like an oversight.
*/

-- Enqueue --------------------------------------------------------------------------------

/*
  Preferences are checked here and again at send time.

  Here, so an opted out person never has a row written that describes something they asked
  not to hear about. Again at send, because a queue drained on a timer can hold a row
  across the moment somebody changes their mind, and the later answer is the right one.
*/
create or replace function public.enqueue_email(
  p_kind text,
  p_profile_id uuid,
  p_dedupe_key text,
  p_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  wants boolean;
begin
  if p_profile_id is null then
    return;
  end if;

  select case p_kind
    when 'story_published' then story_published
    when 'story_featured' then story_featured
    when 'comment_reply' then comment_reply
    else false
  end
  into wants
  from public.notification_prefs
  where profile_id = p_profile_id;

  /* No preferences row means no profile, or a profile mid creation. Say nothing. */
  if wants is null or wants = false then
    return;
  end if;

  insert into public.email_outbox (kind, profile_id, dedupe_key, payload)
  values (p_kind, p_profile_id, p_dedupe_key, p_payload)
  on conflict (dedupe_key) do nothing;
end;
$$;

revoke all on function public.enqueue_email(text, uuid, text, jsonb) from public, anon, authenticated;

-- Story published, and story featured -----------------------------------------------------

/*
  Anonymous is about the byline, not about the author. Somebody who asked not to be named
  still wants to know their story went up, so this reads author_id and ignores
  is_anonymous. The email says so in as many words.
*/
create or replace function public.notify_disaster_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  was_published boolean := tg_op = 'UPDATE' and old.status = 'published';
  was_featured boolean := tg_op = 'UPDATE' and old.featured_at is not null;
begin
  if new.status = 'published' and not was_published then
    perform public.enqueue_email(
      'story_published',
      new.author_id,
      'story_published:' || new.id::text,
      jsonb_build_object('disaster_id', new.id, 'slug', new.slug, 'title', new.title, 'line', new.line)
    );
  end if;

  if new.featured_at is not null and not was_featured then
    perform public.enqueue_email(
      'story_featured',
      new.author_id,
      'story_featured:' || new.id::text,
      jsonb_build_object('disaster_id', new.id, 'slug', new.slug, 'title', new.title, 'line', new.line)
    );

    /*
      The Featured badge is seeded as manual because there was no rule that could grant
      it. Featuring a story is that rule, so the grant is recorded as manual: a person
      decided, the database only wrote it down.
    */
    if new.author_id is not null then
      insert into public.badge_grants (profile_id, badge_id, source, note)
      values (new.author_id, 'featured', 'manual', 'Story ' || new.id::text || ' went on the front page')
      on conflict (profile_id, badge_id) do nothing;
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.notify_disaster_change() from public, anon, authenticated;

create trigger disasters_notify
after insert or update on public.disasters
for each row execute function public.notify_disaster_change();

-- Comment replies --------------------------------------------------------------------------

/*
  Only visible replies, and never a reply to yourself.

  Held is deliberate. A comment waiting on a look has not happened yet as far as the
  person being replied to is concerned, and mailing them about something they cannot see
  is how a moderation queue leaks. If it clears the hold the update trigger picks it up.
*/
create or replace function public.notify_comment_reply()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  parent_author uuid;
begin
  if new.parent_id is null or new.status <> 'visible' then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.status = 'visible' then
    return new;
  end if;

  select author_id into parent_author from public.comments where id = new.parent_id;

  if parent_author is null or parent_author = new.author_id then
    return new;
  end if;

  perform public.enqueue_email(
    'comment_reply',
    parent_author,
    'comment_reply:' || new.id::text,
    jsonb_build_object(
      'comment_id', new.id,
      'parent_id', new.parent_id,
      'target_kind', new.target_kind,
      'target_key', new.target_key,
      'excerpt', left(new.body_markdown, 280)
    )
  );

  return new;
end;
$$;

revoke all on function public.notify_comment_reply() from public, anon, authenticated;

create trigger comments_notify_reply
after insert or update of status on public.comments
for each row execute function public.notify_comment_reply();

-- Unsubscribe ------------------------------------------------------------------------------

/*
  One click means one request, from a mail client, with no session.

  The token is already on notification_prefs. This function is what the unsubscribe route
  calls: it turns a token plus a kind into a single false, and returns whether it matched
  so the route can tell a real link from a guess without leaking which.

  Rotating the token on use would break the other two links in older emails, so it stays.
  A leaked token can only turn somebody's email off, which is the failure worth having.
*/
create or replace function public.unsubscribe_by_token(p_token uuid, p_kind text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  hit integer;
begin
  update public.notification_prefs
  set
    story_published = case when p_kind in ('story_published', 'all') then false else story_published end,
    story_featured  = case when p_kind in ('story_featured', 'all') then false else story_featured end,
    comment_reply   = case when p_kind in ('comment_reply', 'all') then false else comment_reply end,
    updated_at = now()
  where unsubscribe_token = p_token;

  get diagnostics hit = row_count;
  return hit > 0;
end;
$$;

revoke all on function public.unsubscribe_by_token(uuid, text) from public, anon, authenticated;
