/*
  v2 schema.

  Everything the rebuild needs that did not exist before: people, their stories, the
  conversation around them, and the badges that record who was in the room.

  Two rules run through all of it.

  Writes go through Astro API routes using the service role, not straight from the
  browser. Likes need an IP hashed with a server side secret, comments need rate limits
  and a hold on brand new GitHub accounts, and a submission needs a title written for it.
  None of that can be enforced from the client, so RLS below is read only for anon and
  authenticated, and the routes are the only writers. The two exceptions are a person
  editing their own profile and their own notification preferences, which are safe to do
  directly and would otherwise cost two routes for nothing.

  Content is keyed by its collection id, never by its URL. A URL contains a topic, topics
  are a judgement call recorded in src/config/taxonomy.json, and that judgement will get
  revised. Comments and likes must survive that.
*/

-- Content targets ----------------------------------------------------------------------

/*
  What a comment or a like can be attached to.

  `content` covers articles and videos, keyed by the collection id in the content
  submodule, for example `blog/why-i-left-medium` or `videos/dQw4w9WgXcQ`. `disaster`
  covers dev disasters, keyed by the disaster id as text. Drips are deliberately absent:
  decision 8 keeps that conversation on dotnetdrip.com.
*/
create type public.target_kind as enum ('content', 'disaster');

-- Profiles -----------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,

  /*
    The handle in /builders/[handle]. Seeded from the GitHub login and lowercased, and
    checked against the reserved list so nobody can claim /about or /submit. Mutable,
    because people rename themselves, which is also why nothing else keys off it.
  */
  handle text not null unique,
  display_name text,
  avatar_url text,
  bio text,

  /*
    User supplied links, rendered nofollow. An array of { label, url } rather than fixed
    columns, because the list of places a developer lives changes faster than a schema.
  */
  links jsonb not null default '[]'::jsonb,

  /*
    Decision 14. A private profile still exists and still owns its stories, it just does
    not render a public page.
  */
  is_private boolean not null default false,

  /*
    Captured at sign in. github_created_at is what the new account hold in decision 16
    reads, so it has to be stored rather than fetched at comment time.
  */
  github_id bigint unique,
  github_login text,
  github_created_at timestamptz,

  /*
    Captured at link time, not matched on login. streamEvents keys on a Twitch login and
    logins change, so matching by name would silently drop exactly the long time
    community members the badge backfill exists to reward.
  */
  twitch_user_id text unique,
  twitch_login text,
  twitch_linked_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  /* Decision 17. Deletion has to actually work, and it has to leave the comment tree
     readable, so the row is tombstoned here and the auth user is deleted separately. */
  deleted_at timestamptz,

  constraint profiles_handle_shape check (handle ~ '^[a-z0-9][a-z0-9-]{0,38}$'),
  constraint profiles_links_is_array check (jsonb_typeof(links) = 'array')
);

create index profiles_handle_live_idx on public.profiles (handle) where deleted_at is null;
create index profiles_twitch_idx on public.profiles (twitch_user_id) where twitch_user_id is not null;

-- Bans ---------------------------------------------------------------------------------

/*
  Decision 16's ban flag, as a table rather than a boolean, so a ban carries a reason and
  a date. A row here means banned. expires_at null means permanent.
*/
create table public.bans (
  profile_id uuid primary key references public.profiles (id) on delete cascade,
  reason text not null,
  banned_at timestamptz not null default now(),
  expires_at timestamptz
);

-- Dev disasters ------------------------------------------------------------------------

create table public.disasters (
  /*
    The diagnostic code the design prints as 003. Sequential and never reused, which is
    why it is an identity column and not a uuid.
  */
  id bigint primary key generated by default as identity,

  /* AI written on submit alongside the title, editable in Studio. Null until approved. */
  slug text unique,

  /*
    Decision 35. Severity and the id above are the entire classification. There is
    deliberately no topic column here, and adding one later would break that decision
    quietly rather than loudly.
  */
  severity text not null check (severity in ('error', 'warning', 'info', 'hint')),

  /*
    Decision 25. Neither of these is user supplied. The title is a mono label, the line
    is the sentence people remember and the thing the wall renders as the headline.
  */
  title text,
  line text,

  /* Decision 6. Freeform prose, exactly as it was typed. */
  body text not null,

  /*
    Decision 6 again. Nullable and unasked for at submit time, so the shape is here the
    day someone decides to ask for it, without a migration on a table with real rows.
  */
  blast_radius text,
  time_to_recover text,
  tags text[],

  /* Null when told anonymously, and also after the teller deletes their account. */
  author_id uuid references public.profiles (id) on delete set null,
  is_anonymous boolean not null default false,

  /* Decision 7. Pre moderated, moved along by hand in Studio. */
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  moderation_note text,

  submitted_at timestamptz not null default now(),
  published_at timestamptz,
  updated_at timestamptz not null default now(),

  /* A published disaster is a URL, so it needs everything a URL needs. */
  constraint disasters_published_is_complete check (
    status <> 'published'
    or (slug is not null and title is not null and line is not null and published_at is not null)
  )
);

create index disasters_wall_idx on public.disasters (published_at desc) where status = 'published';
create index disasters_severity_idx on public.disasters (severity) where status = 'published';
create index disasters_author_idx on public.disasters (author_id) where author_id is not null;

-- Comments -----------------------------------------------------------------------------

create table public.comments (
  id uuid primary key default gen_random_uuid(),

  target_kind public.target_kind not null,
  target_key text not null,

  /*
    Decision 9 allows one level of threading. A reply points at a top level comment and
    nothing points at a reply, which the trigger below enforces. Depth limits that live
    only in the UI stop being limits the first time someone posts through the API.
  */
  parent_id uuid references public.comments (id) on delete cascade,

  author_id uuid not null references public.profiles (id) on delete cascade,
  body_markdown text not null,

  /*
    visible   published and readable
    held      caught by the new account hold, waiting on a look
    hidden    auto hidden by reports, or hidden in Studio
    deleted   soft deleted by its author, renders as a tombstone
  */
  status text not null default 'visible' check (status in ('visible', 'held', 'hidden', 'deleted')),

  /* Denormalised so the auto hide threshold does not need a count on every insert. */
  report_count integer not null default 0,

  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,

  constraint comments_body_length check (char_length(body_markdown) between 1 and 10000),
  constraint comments_deleted_has_time check ((status = 'deleted') = (deleted_at is not null))
);

create index comments_thread_idx on public.comments (target_kind, target_key, created_at);
create index comments_parent_idx on public.comments (parent_id) where parent_id is not null;
create index comments_author_recent_idx on public.comments (author_id, created_at desc);

create or replace function public.comments_enforce_one_level()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  grandparent uuid;
begin
  if new.parent_id is null then
    return new;
  end if;

  select parent_id into grandparent from public.comments where id = new.parent_id;

  if not found then
    raise exception 'Parent comment % does not exist', new.parent_id;
  end if;

  if grandparent is not null then
    raise exception 'Comments thread one level deep. Reply to the top of the thread instead.';
  end if;

  return new;
end;
$$;

create trigger comments_one_level
before insert or update of parent_id on public.comments
for each row execute function public.comments_enforce_one_level();

-- Likes --------------------------------------------------------------------------------

/*
  Decision 11. No sign in, so there is no honest unique key here, only a good enough one.

  A like is unique per target per browser token per hashed IP. Clearing site data or
  moving network lets somebody like a second time, and that is the accepted cost of not
  asking readers to log in to say "yes, this". Hashing the IP rather than deduping on it
  alone is deliberate: an office, a school or a household behind one NAT are many people,
  and a bare IP unique index would let the first of them silence the rest.

  ip_hash is HMAC of the address with a server side secret that rotates, so the column is
  a dedupe token and not a stored IP address.
*/
create table public.likes (
  id uuid primary key default gen_random_uuid(),

  target_kind public.target_kind not null,
  target_key text not null,

  browser_token text not null,
  ip_hash text not null,

  /* Attribution when signed in. The like still counts once either way. */
  profile_id uuid references public.profiles (id) on delete set null,

  created_at timestamptz not null default now()
);

create unique index likes_dedupe_idx
  on public.likes (target_kind, target_key, browser_token, ip_hash);

create unique index likes_profile_dedupe_idx
  on public.likes (target_kind, target_key, profile_id)
  where profile_id is not null;

create index likes_target_idx on public.likes (target_kind, target_key);
create index likes_flood_idx on public.likes (ip_hash, created_at desc);

-- Reports ------------------------------------------------------------------------------

/*
  Decision 16, and the reason /report is a page rather than a modal. Every Report control
  on the site is a link to that page with the target prefilled, so reporting works with
  JavaScript off, is linkable, and is survivable when the thing being reported is the
  page you are standing on.
*/
create table public.reports (
  id uuid primary key default gen_random_uuid(),

  kind text not null check (kind in ('comment', 'disaster', 'profile', 'conduct', 'other')),

  /* Comment or disaster id, profile handle, or a site path for anything else. */
  target_ref text,

  reason text not null,
  details text,

  /* Null for an anonymous report. Reporting never requires an account. */
  reporter_id uuid references public.profiles (id) on delete set null,
  reporter_email text,

  status text not null default 'open' check (status in ('open', 'actioned', 'dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index reports_open_idx on public.reports (created_at desc) where status = 'open';
create index reports_target_idx on public.reports (kind, target_ref);

/*
  The auto hide threshold. Reports are cheap to file and a comment that several different
  people have flagged should stop being visible before a human gets to it, not after.
  Hiding is reversible and deliberately not destructive.
*/
create or replace function public.reports_auto_hide()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  threshold constant integer := 3;
  target uuid;
begin
  if new.kind <> 'comment' or new.target_ref is null then
    return new;
  end if;

  begin
    target := new.target_ref::uuid;
  exception when invalid_text_representation then
    return new;
  end;

  update public.comments
     set report_count = report_count + 1,
         status = case when status = 'visible' and report_count + 1 >= threshold then 'hidden' else status end
   where id = target;

  return new;
end;
$$;

create trigger reports_hide_comment
after insert on public.reports
for each row execute function public.reports_auto_hide();

-- Badges -------------------------------------------------------------------------------

create table public.badges (
  id text primary key,
  name text not null,
  description text not null,

  /*
    Grouping for the shelf on a profile. `presence` is time in the room, `craft` is
    things made, `care` is things done for other people.
  */
  category text not null check (category in ('presence', 'craft', 'care')),

  /* Rendered as the diagnostic squiggle colour, so it reuses the severity vocabulary. */
  tone text not null default 'info' check (tone in ('error', 'warning', 'info', 'hint')),

  sort_order integer not null default 0,

  /* True when there is no rule, only Michael deciding. */
  is_manual boolean not null default false,

  created_at timestamptz not null default now()
);

create table public.badge_grants (
  profile_id uuid not null references public.profiles (id) on delete cascade,
  badge_id text not null references public.badges (id) on delete cascade,

  /* auto: earned on site. backfill: found in the Twitch history. manual: granted. */
  source text not null default 'auto' check (source in ('auto', 'backfill', 'manual')),
  note text,

  granted_at timestamptz not null default now(),

  primary key (profile_id, badge_id)
);

create index badge_grants_profile_idx on public.badge_grants (profile_id, granted_at);

-- Notification preferences ---------------------------------------------------------------

/*
  Decision 15. Three email types, opt out per type, and one click unsubscribe, which is
  what the token is for. An unsubscribe link that demands a sign in is not an unsubscribe
  link.
*/
create table public.notification_prefs (
  profile_id uuid primary key references public.profiles (id) on delete cascade,

  story_published boolean not null default true,
  story_featured boolean not null default true,
  comment_reply boolean not null default true,

  unsubscribe_token uuid not null default gen_random_uuid() unique,
  updated_at timestamptz not null default now()
);

-- Sign up ------------------------------------------------------------------------------

/*
  A new GitHub sign in becomes a profile and a set of notification preferences in the same
  transaction, so no code path anywhere has to cope with a signed in person who has no
  profile row.

  The handle starts as the GitHub login and gains a numeric suffix if that is taken or
  reserved. Reserved names are checked against the same list the router uses, kept in
  public.reserved_handles below so the database can enforce it too.
*/
create table public.reserved_handles (
  handle text primary key
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base text;
  candidate text;
  suffix integer := 0;
begin
  base := lower(coalesce(
    new.raw_user_meta_data ->> 'user_name',
    new.raw_user_meta_data ->> 'preferred_username',
    split_part(coalesce(new.email, 'builder'), '@', 1)
  ));

  base := regexp_replace(base, '[^a-z0-9-]', '-', 'g');
  base := regexp_replace(base, '-+', '-', 'g');
  base := trim(both '-' from base);
  if base = '' or base is null then
    base := 'builder';
  end if;
  base := left(base, 32);

  candidate := base;
  while exists (select 1 from public.reserved_handles where handle = candidate)
     or exists (select 1 from public.profiles where handle = candidate) loop
    suffix := suffix + 1;
    candidate := base || '-' || suffix;
  end loop;

  insert into public.profiles (id, handle, display_name, avatar_url, github_id, github_login, github_created_at)
  values (
    new.id,
    candidate,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', base),
    new.raw_user_meta_data ->> 'avatar_url',
    nullif(new.raw_user_meta_data ->> 'provider_id', '')::bigint,
    new.raw_user_meta_data ->> 'user_name',
    nullif(new.raw_user_meta_data ->> 'created_at', '')::timestamptz
  );

  insert into public.notification_prefs (profile_id) values (new.id);

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- updated_at -----------------------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

create trigger disasters_touch before update on public.disasters
  for each row execute function public.touch_updated_at();

create trigger notification_prefs_touch before update on public.notification_prefs
  for each row execute function public.touch_updated_at();
