name: Nightly Deployment
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Trigger Netlify Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Build Hook
        shell: bash
        run: |
          curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}